### ISSUE TITLE
[omnisci-datascience-installer] Change the name of the package to omnisci-datascience

### ISSUE THREAD

**Issue by xmnlab** [Quansight/mapd#148]
## Justification

As "default_prefix" is not working to "pkg", and the target parent directory is $HOME now, we can remove "default_prefix" and just change the name of the project to omnisci-datascience.

## Request (General goal)

- [x] Remove "default_prefix" 
- [x] Change the name of the project to omnisci-datascience

## Stakeholders

@israelvicars @andrewseidl 

## References

- https://github.com/Quansight/omnisci-datascience-installer/issues/52

**Comment by israelvicars** [comment]
Confirmed as resolved in 0.1.4 ✅
