### ISSUE TITLE
[omnisci-examples] Change default ports to match the same configuration used by Mac Preview 

### ISSUE THREAD

**Issue by xmnlab** [Quansight/mapd#149]
## Justification

Currently, the ports used by omnisci-examples docker-compose and notebooks are not the same used by Mac Preview.

## Request (General goal)

1. Change the docker-compose configuration to use the same ports used by Mac Preview
2. Change the notebooks that connects to the local OmniSciDB server. 

```
For omnisci.conf:
  port = 16274
  http-port = 16278
  calcite-port = 16279
```

```
For docker compose:
    image: omnisci/core-os-cpu:v5.5.0
    ports:
      - 16274:16274
      - 16278:16278
``` 

## Stakeholders

@israelvicars  @andrewseidl

**Comment by xmnlab** [comment]
This issue was resolved in the last version on omnisci-examples (https://github.com/Quansight/omnisci-examples/blob/master/docker-compose.yml)

PS: Changing the ports on `omnisci.conf` didn't work for me, so I just changed the port for the host in the docker-compose recipe (e.g. `16274:6274`).

@israelvicars could you confirm that this issue can be closed as resolved? thanks!

**Comment by israelvicars** [comment]
Confirmed @xmnlab ! Thanks!
