### ISSUE TITLE
[omnisci-examples][desktop] OmniSciDB Connection Template Notebook

### ISSUE THREAD

**Issue by israelvicars** [Quansight/mapd#150]
## Justification

Provide the user a starting point for a new Jupyter Lab notebook.

## Request (General goal)

Add a template notebook to the installer example notebooks (`00_Connection_Template.ipynb`) that provides the user a starting point for initializing a connection to the desktop edition OmniSciDB.

![CleanShot 2021-02-16 at 22 42 39](https://user-images.githubusercontent.com/1076105/108219920-33ee5f80-7104-11eb-85b8-a1bebd288612.png)

## Stakeholders

@tmostak

## Technical Specification

File name: `00_Connection_Template.ipynb`

Connection details: `user='admin', password='HyperInteractive', host='127.0.0.1', port=16274, dbname='omnisci'`

Example (actual):
[00_Connection_Template.ipynb.zip](https://github.com/Quansight/omnisci/files/5996430/00_Connection_Template.ipynb.zip)

**Comment by niviksha** [comment]
@xmnlab @israelvicars we should make this an ibis connection rather than a pymapd connection, since we can always get the underlying pymapd connection from the ibis connection
